### ISSUE TITLE
Getting by empty string UUID is not handeled well

### ISSUE THREAD

**Issue by tbabej** [robgolding63/tasklib#28]
Consider following snippet:

```
>>> from tasklib.task import TaskWarrior
>>> tw = TaskWarrior()
>>> tw.tasks.get(uuid='')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/tasklib/task.py", line 619, in get
ValueError: get() returned more than one Task -- it returned 6! Lookup parameters were {'uuid': ''}
>>> 
```

**Comment by tbabej** [comment]
Fixed with: 0110af91cb5bf3804efc35cb50c8430419af4313.
